// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8aTXFqUNRph7-Q1rJpHqSGFF7lzakcs',
    appId: '1:860956288755:web:e95a5b86250edf8674b986',
    messagingSenderId: '860956288755',
    projectId: 'fishingtool-c8aaa',
    authDomain: 'fishingtool-c8aaa.firebaseapp.com',
    storageBucket: 'fishingtool-c8aaa.appspot.com',
    measurementId: 'G-JNFQ33KQNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmV5INNv941VbN_4c9abgc3bkySCf6N-Y',
    appId: '1:860956288755:android:af21fb4525274a0f74b986',
    messagingSenderId: '860956288755',
    projectId: 'fishingtool-c8aaa',
    storageBucket: 'fishingtool-c8aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPTHjttQfTMrMtmXLegxB3SOfiJ0uODk',
    appId: '1:860956288755:ios:4416baf444e6cb9174b986',
    messagingSenderId: '860956288755',
    projectId: 'fishingtool-c8aaa',
    storageBucket: 'fishingtool-c8aaa.appspot.com',
    iosBundleId: 'com.example.fishingTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPTHjttQfTMrMtmXLegxB3SOfiJ0uODk',
    appId: '1:860956288755:ios:2901032584b0bd8174b986',
    messagingSenderId: '860956288755',
    projectId: 'fishingtool-c8aaa',
    storageBucket: 'fishingtool-c8aaa.appspot.com',
    iosBundleId: 'com.example.fishingTool.RunnerTests',
  );
}
