//import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// class Database{
  
// }

class Fishes{
  int id;
  String name;
  bool king;
  String memo;
  bool inMyPond;
  DateTime createdAt;

  Fishes({
    required this.id,
    required this.name,
    required this.king,
    required this.memo,
    required this.inMyPond,
    required this.createdAt,

  });

  factory Fishes.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Fishes(
        id: data?['id'],
        name: data?['name'],
        king: data?['king'],
        memo: data?['memo'],
        inMyPond: data?['inMyPond'],
        createdAt: data?['createdAt'].toDate());
  }

  Map<String, dynamic> toFirestore() {
    return {
      "id": id,
      "name": name,
      "king": king,
      "memo": memo,
      "inMyPond": inMyPond,
      "createdAt": createdAt,
    };
  }
}

List<Fishes> MyFish = [
  Fishes(id: 1, name: "ゴクラクギョ・青", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 2, name: "ゴクラクギョ・赤", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 3, name: "ゴクラクギョ・黄", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 4, name: "ゴクラクギョ・白", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 5, name: "ゴクラクギョ・黒", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 6, name: "ポンポンベタ・白赤", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 7, name: "ポンポンベタ・青赤", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 8, name: "ハーフムーン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 9, name: "ワカサギ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 10, name: "グッピー・青", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 11, name: "グッピー・赤", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 12, name: "キンギョ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 13, name: "キンギョ・白赤", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 14, name: "デメキン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 15, name: "ランチュウ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 16, name: "ドンコ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 17, name: "エンゼルフィッシュ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 18, name: "にじいろフィッシュ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 19, name: "オイカワ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 20, name: "コリドラス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 21, name: "グラスキャット", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 22, name: "ウグイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 23, name: "フナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 24, name: "ツチフキ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 25, name: "ピラニア", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 26, name: "イチゴヤドクガエル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 27, name: "クラウンローチ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 28, name: "ウーパールーパー", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 29, name: "ペンシルフィッシュ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 30, name: "ブラックゴースト", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 31, name: "アユ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 32, name: "ミナミイシガメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 33, name: "ネオンテトラ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 34, name: "カージナルテトラ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 35, name: "モモ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 36, name: "サカサナマズ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 37, name: "ドワーフグラミー", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 38, name: "エレファントノーズ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 39, name: "ヤマメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 40, name: "ブルーギル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 41, name: "ニジマス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 42, name: "ブラックバス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 43, name: "カンディル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 44, name: "イワナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 45, name: "サケ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 46, name: "ウナギ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 47, name: "コイ・黒", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 48, name: "コイ・金", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 49, name: "ニシキゴイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 50, name: "ゼブラキャット", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 51, name: "イエローパーチ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 52, name: "カエル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 53, name: "アカガエル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 54, name: "サクラマス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 55, name: "ポリプテルス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 56, name: "アロワナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 57, name: "レッドアロワナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 58, name: "グリーンアロワナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 59, name: "ゴールデンアロワナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 60, name: "シルバーアロワナ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 61, name: "イトウ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 62, name: "オオサンショウウオ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 63, name: "オオナマズ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 64, name: "エンゼルウナギ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 65, name: "電気ウナギ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 66, name: "ネオケラトドゥス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 67, name: "ピラルク", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 68, name: "パーカーホ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 69, name: "ジムナーカス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 70, name: "コチョウザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 71, name: "プラークラベーン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 72, name: "テムノドント", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 73, name: "パイク", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 74, name: "キングサーモン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 75, name: "ムベンガ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 76, name: "チョウザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 77, name: "プラー・ブック", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 78, name: "サルコスクス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 79, name: "ハイネリア", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 80, name: "クマノミ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 81, name: "リトルマリン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 82, name: "ハナゴイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 83, name: "アジ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 84, name: "トビウオ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 85, name: "タツノオトシゴ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 86, name: "ナンヨウハギ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 87, name: "サンマ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 88, name: "ミノカサゴ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 89, name: "ハリセンボン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 90, name: "ゴマフビウミウシ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 91, name: "ホタテ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 92, name: "サザエ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 93, name: "ウニ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 94, name: "クリオネ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 95, name: "ヒトデ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 96, name: "クラゲ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 97, name: "イシダイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 98, name: "カサゴ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 99, name: "タイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 100, name: "フグ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 101, name: "サバ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 102, name: "カツオ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 103, name: "ヒラメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 104, name: "メバル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 105, name: "ミドリフサアンコウ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 106, name: "ブロブフィッシュ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 107, name: "カレイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 108, name: "スイカ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 109, name: "リーフシードラゴン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 110, name: "ホッケ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 111, name: "アイナメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 112, name: "スズキ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 113, name: "チョウチンアンコウ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 114, name: "ネコザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 115, name: "マグロ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 116, name: "フウセンウナギ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 117, name: "ブルーナポレオン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 118, name: "シーラカンス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 119, name: "イクチオサウルス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 120, name: "ホシザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 121, name: "ラブカ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 122, name: "シロザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 123, name: "ヨロイザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 124, name: "ホシエイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 125, name: "アルビノホシエイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 126, name: "アカマンボウ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 127, name: "マンボウ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 128, name: "タマカイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 129, name: "シイラ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 130, name: "カジキ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 131, name: "マンタ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 132, name: "ミツクリザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 133, name: "ホオジロザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 134, name: "マオナガ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 135, name: "シュモクザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 136, name: "ジンベエザメ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 137, name: "リュウグウノツカイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 138, name: "ノコギリエイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 139, name: "ノコギリエイ・黄", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 140, name: "エラスモサウルス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 141, name: "ダンクルオステウス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 142, name: "リードシクティス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 143, name: "メガロドン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 144, name: "プラテカルプス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 145, name: "オオシャコガイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 146, name: "メガマウス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 147, name: "アーケロン", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 148, name: "ヤドカリ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 149, name: "ビーシュリンプ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 150, name: "ザリガニ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 151, name: "イセエビ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 152, name: "ズワイガニ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 153, name: "アノマロカリス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 154, name: "メンダコ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 155, name: "コウモリダコ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 156, name: "イカ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 157, name: "タコ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 158, name: "オウムガイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 159, name: "アンモナイト", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 160, name: "オーグリグラマ・黄", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 161, name: "ウェナーフェイス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 162, name: "エルトナヤッコ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 163, name: "ドワエンゼル", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 164, name: "プククリ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 165, name: "レンダーコリス", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 166, name: "ながぐつ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 167, name: "旬のマグロ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 168, name: "旬のカジキ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 169, name: "旬のスイカ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 170, name: "旬のイカ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 171, name: "旬の黄金イカ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 172, name: "旬のイセエビ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 173, name: "旬の黄金イセエビ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 174, name: "旬の本マグロ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 175, name: "旬の黄金本マグロ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 176, name: "旬のマダイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 177, name: "旬の黄金マダイ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 178, name: "旬のエビ", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
  Fishes(id: 179, name: "えびせん", king: false, memo: "", inMyPond: false, createdAt: DateTime.now()),
];
